version: '3'

services:
   db:
      image: postgres
   web:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes: 
         - .:/code
      ports:
         - "8000:8000"
      depends_on:
         - db
      environment:
         - SKYSCANNER_KEY=$SKYSCANNER_KEY
         - AMADEUS_CLIENT_ID=$AMADEUS_CLIENT_ID
         - AMADEUS_CLIENT_SECRET=$AMADEUS_CLIENT_SECRET
         - GOOGLE_MAPS_KEY=$GOOGLE_MAPS_KEY
         - AMADEUS_SANDBOX_KEY=$AMADEUS_SANDBOX_KEY

